#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 30 16:43:48 2020

@author: Dequan
"""

import d2lzh as d2l
from mxnet import gluon, init
from mxnet.gluon import loss as gloss, nn
from mxnet import autograd, nd

# load data
batch_size = 256
num_inputs = 784
num_outputs = 10

train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

# define model
net = nn.Sequential()
net.add(nn.Dense(10))
net.initialize(init.Normal(sigma=0.01))

# loss function
loss = gloss.SoftmaxCrossEntropyLoss()

# algo

trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': 0.1})
num_epochs = 5
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None,
              None, trainer)

