" Sets how many lines of history VIM has to remember
set history=700
" Enable filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from the outside
set autoread

highlight LineNr term=Bold cterm=NONE ctermfg=darkgrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE guibg=White
set smartindent
autocmd InsertEnter * se cul
"set mouse=a
set nu
set ruler
set showmatch
set laststatus=2
syntax on
set tabstop=4
set hlsearch      
set incsearch
set viminfo='20,<10000
hi CursorLine   cterm=Bold ctermbg=none ctermfg=none guibg=lightred guifg=white
hi CursorColumn cterm=Bold ctermbg=black ctermfg=red guibg=lightred guifg=white
hi SpellBad     cterm=Bold ctermbg=lightgreen ctermfg=red guibg=lightred guifg=white
"nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
let g:jedi#completions_command = "<C-N>"
" Enable folding
set foldmethod=indent
set foldlevel=99
nnoremap <space> za
"Plugin 'tmhedberg/SimpylFold'
"Plugin 'davidhalter/jedi-vim'
